### ISSUE TITLE
Este tema tem licença open source?

### ISSUE THREAD

**Issue by ramirezemerick88** [thomazot/qcola#1]
Olá Thomaz, estou testando o sistema da tray e gostaria de saber se este tema que você criou pode ser utilizado com licença open source.
Att;

**Comment by thomazot** [comment]
Opa, se alterar a indentidade visual fica a vontade. altera as cores e logo fica de boa.

**Comment by ramirezemerick88** [comment]
Obrigado Thomaz, ficou muito bem escrito seu código!
